---
title: "AdamMarkers"
author: "HB"
date: "7/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 120),
  message = FALSE,
  warning = FALSE
)
```

### Allocate memory  and use all CPUs

```{r}
library(future)
plan(strategy = "multiprocess", workers = 8)
options(future.globals.maxSize = 20 * 1024 ^ 3)

library("future.apply")
library("stats")
```


```{r simplePlots}
# Copied from Adam's email:
genes <- c("CD3E","CD3D","CD3G","CD4","IL7R","CCR7","IL2RA","ICOS","PDCD1","CXCR1","CXCR2","CXCR3","CXCR4","CXCR5",
           "CXCR6","CX3CR1","CCR1","CCR2","CCR3","CCR4","CCR5","CCR6","CCR7","CCR8","CCR9","CCR10",
           "TNFRSF4","TNFRSF9","CTLA4","CD160","LAG3","CD244","BTLA","TNFRSF18","HAVCR2","TIGIT",
           "KLRB1","KLRK1","NCR1","NCR2","NCR3","KIT","PTGDR2","ITGA4","ITGAE","KIR2DL1","KLRD1","RORC","TBX21") # 49


library(Matrix)
setwd("~/__Data")
normalizedPBMC <- get(load("SeuratNormalizedCounts_GRCh38_filteredMT.RData"))

PBMC.IDs <- unlist(lapply(strsplit(colnames(normalizedPBMC), "-"), function(x) x[1]))

setwd("~/__Data")
CLs <- read.csv("clusters.csv", as.is=TRUE)
clusterIDs <- unlist(lapply(strsplit(CLs$Barcode, "-"), function(x) x[1]))
CLs <- CLs[match(PBMC.IDs, clusterIDs), ]
CLs$Barcode <- colnames(normalizedPBMC)
colnames(CLs) <- c("ID", "group")
CLs$group<- as.factor(CLs$group)

cl3 <- CLs$ID[which(CLs$group == 3)] # 23,483 across ALL timepoints & samples
not3 <- setdiff(CLs$ID, cl3) # 102,071
notT <- CLs$ID[which(CLs$group != 3 & CLs$group != 4 & CLs$group != 1)] # 49,816
not.cl3.T <- CLs$ID[which(CLs$group != 3 & CLs$group != 1)] # 63,203
Tnaive <- CLs$ID[which(CLs$group == 1)] # 38,868

expTbl <- normalizedPBMC[genes, ]

pdf("~/__Plots/Adam_markerExpPlots.pdf")
for (i in 1:length(genes)) {
plot(density(expTbl[i, not3]), col=rgb(0,0.65,1,0.5), lwd=5, main=paste0(genes[i]),
     xlab=paste0(genes[i], " normalized expression"))
lines(density(expTbl[i, cl3]), col=rgb(1,0.25,0,0.55), lwd=5)
legend("topright", legend=c("cluster 3", "others"), pch=15, 
       col=c(rgb(1,0.25,0,0.55), rgb(0,0.65,1,0.5)), bty='n')
}

pdf("~/__Plots/Adam_markerExpPlots_cfNonT.pdf")
for (i in 1:length(genes)) {
plot(density(expTbl[i, notT]), col=rgb(0,0.65,1,0.5), lwd=5, main=paste0(genes[i]),
     xlab=paste0(genes[i], " normalized expression"))
lines(density(expTbl[i, cl3]), col=rgb(1,0.25,0,0.55), lwd=5)
legend("topright", legend=c("cluster 3", "not T"), pch=15, 
       col=c(rgb(1,0.25,0,0.55), rgb(0,0.65,1,0.5)), bty='n')
}

expTbl2 <- expTbl[ , grep("-2h$", colnames(expTbl))] # 25749 cells
pdf("~/__Plots/Adam_markerExpPlots_2hrOnly.pdf")
for (i in 1:length(genes)) {
plot(density(expTbl2[i, intersect(not3, colnames(expTbl2))]), col=rgb(0,0.65,1,0.5), lwd=5, main=paste0(genes[i]),
     xlab=paste0(genes[i], " normalized expression"))
lines(density(expTbl2[i, intersect(cl3, colnames(expTbl2))]), col=rgb(1,0.25,0,0.55), lwd=5)
legend("topright", legend=c("cluster 3", "others"), pch=15, 
       col=c(rgb(1,0.25,0,0.55), rgb(0,0.65,1,0.5)), bty='n')
}

```

## Focus on specific subsets of cells

```{r subPops}
CD3 <- ((expTbl["CD3D", ] * expTbl["CD3E", ]) * expTbl["CD3G", ])^(1/3)
H = hist(CD3, breaks=100, col=rgb(0,0.65,1,0.25), border="white") # CD3 only 0 or > 0.5

CD3.pos <- names(which(CD3 > 0.5))  62410

# H = hist(normalizedPBMC["FOXP3", CD3.pos], breaks=100, , col=rgb(0,0.65,1,0.25), border="white")

FOXP3 <- names(which(normalizedPBMC["FOXP3", CD3.pos] > 0.5)) # 1,296 Tregs
TBX21 <- names(which(normalizedPBMC["TBX21", CD3.pos] > 0.5)) # 3,867 Th1
RORC <- names(which(normalizedPBMC["RORC", CD3.pos] > 0.5)) # 1,101 Th1x7
GATA3 <- names(which(normalizedPBMC["GATA3", CD3.pos] > 0.5)) # 18,740 Th2
IRF4 <- names(which(normalizedPBMC["IRF4", CD3.pos] > 0.5)) # 1,082 ???

selPops <- list(FOXP3, TBX21, RORC, GATA3, IRF4)
labs <- c("FOXP3", "TBX21", "RORC", "GATA3", "IRF4")

pdf("~/__Plots/Adam_markerExpPlots_selPops_cf.not.cl3.T.pdf")
for (j in 1:length(selPops)) {
   for (i in 1:length(genes)) {
      plot(density(expTbl[i, not.cl3.T]), col=rgb(0,0.65,1,0.5), lwd=5, main=paste0(genes[i]),
           xlab=paste0(genes[i], " normalized expression"))
      lines(density(expTbl[i, selPops[[j]]]), col=rgb(1,0.25,0,0.55), lwd=5)
      legend("topright", legend=c(paste0(labs[j],"+"), "not T"), pch=15, 
             col=c(rgb(1,0.25,0,0.55), rgb(0,0.65,1,0.5)), bty='n')
   }
}

```

## Th17 v Th1

```{r TH17}
TH17 <- c("CD3D","CD3E","CD3G","RORC","STAT3","IL17F","IL23R") # "IL17A",
TH1 <-  c("CD3D","CD3E","CD3G","TBX21","STAT1","IFNG","IL18R1") # CD4

score17 = 1
for (i in 1:length(TH17)) {
   score17 <- score17 * (tanh(normalizedPBMC[TH17[i], ]) + 0.01)
}
score17 <- (score17)^(1/length(TH17))

score1 = 1
for (i in 1:length(TH1)) {
   score1 <- score1 * (tanh(normalizedPBMC[TH1[i], ]) + 0.01)
}
score1 <- (score1)^(1/length(TH1))



setwd("~/__Plots")
pdf("Th1_Th17_scores.pdf")
hist(score17, breaks = 100, border="white", col=rgb(0,0.65,1,0.5)) # select score17 > 0.2, 974 cells
hist(score1,  breaks = 100, border="white", col=rgb(0,0.65,1,0.5)) # select: score1 > 0.11, 23,824 cells

plot(score1, score17, pch=1, cex=0.5, col=rgb(0,0,0,0.25), xlab="Score Th1", ylab="Score Th17")
i17 <- which((score17 > 0.2) & (score1 < 0.11)) 
points((score1[i17]), (score17[i17]), cex=0.6, pch=20, col=rgb(1,0.25,0,0.5))
i1 <- which((score17 < 0.2) & (score1 > 0.11))
points((score1[i1]), (score17[i1]), cex=0.6, pch=20, col=rgb(0,0.75,0.25,0.5))
dev.off()


pdf("~/__Plots/Adam_markerExpDensityPlots_Th1.Th17.v.naive.pdf")
pop17 <- names(which(score17 > 0.2))  #   926
pop1 <- names(which(score1 > 0.11))   # 23233

selPops <- list(th1=pop1, th17=pop17)
popIDs <- c("Th1", "Th17")

for (j in 1:length(selPops)) {
   for (i in 1:length(genes)) {
      plot(density(expTbl[i, notT]), col=rgb(0,0.65,1,0.5), lwd=5, main=paste0(genes[i]),
           xlab=paste0(genes[i], " normalized expression"))
      lines(density(expTbl[i, selPops[[j]]]), col=rgb(1,0.25,0,0.55), lwd=5)
      legend("topright", legend=c(paste0(popIDs[j],"+"), "not T"), pch=15, 
             col=c(rgb(1,0.25,0,0.55), rgb(0,0.65,1,0.5)), bty='n')
   }
}
dev.off()


```