---
title: "CyTOF_pilotPhase2"
author: "HB"
date: "8/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 120),
  message = FALSE,
  warning = FALSE
)
```

### Allocate memory  and use all CPUs

```{r config}
library(future)
plan(strategy = "multiprocess", workers = 8)    ############## set number of CPUs #################
options(future.globals.maxSize = 20 * 1024 ^ 3)

library("future.apply")
library("stats")
```

## 

```{r getData}
setwd("~/__Data/CyTOF/BRI_P2Pilot/")
fNames <- dir(pattern="CSV_")

D0 <- fNames[grep("Day0", fNames)]
D1 <- fNames[grep("Day1", fNames)]
D2 <- fNames[grep("Day2", fNames)]
D3 <- fNames[grep("Day3", fNames)]
D4 <- fNames[grep("Day4", fNames)]
D7 <- fNames[grep("Day7", fNames)]

chex <- fNames[grep("CytoChex", fNames, ignore.case=TRUE)]
hep <- fNames[grep("NaHep", fNames, ignore.case=TRUE)]
 
D0Hep <- intersect(D0, hep)
D0Chex <- intersect(D0, chex)

selSamples <- c(D0Checx, D0Hep, D4)
M = NULL
for (i in 1:length(selSamples)) {
   setwd("~/__Data/CyTOF/BRI_P2Pilot/")
   aFile <- read.csv(fNames[i], header=TRUE, as.is=TRUE)
   rownames(aFile) <- paste0(i, "_", 1:nrow(aFile))
   M <- rbind(M, aFile[sample(1:nrow(aFile), 5000), ])
}

Sys.time()
PCA <- prcomp(M)
Sys.time()

IDs <- unlist(lapply(strsplit(rownames(PCA$x), "_"), function(x) x[1]))

varExp <- summary(PCA)$importance["Proportion of Variance", 1:2]

setwd("~/__Data/CyTOF/BRI_P2Pilot/")
pdf("D0_D4_PCA.pdf", height = 10, width = 10)
plot(PCA$x[ , 1:2], col="white", xlab=paste0("PC1 variance explained = ", varExp[1]),
     ylab=paste0("PC2 variance explained = ", varExp[2]))
points(PCA$x[which(IDs == 1 | IDs == 2 | IDs == 3 | IDs == 4), 1:2], 
      col=rgb(0,0,1,0.25), pch=20)
points(PCA$x[which(IDs == 5 | IDs == 6 | IDs == 7 | IDs == 8), 1:2], 
      col=rgb(0,0.75,0.25,0.25), pch=20)
points(PCA$x[which(IDs == 9 | IDs == 10 | IDs == 11 | IDs == 12), 1:2], 
      col=rgb(1,0,0,0.25), pch=20)
legend("topleft", legend=c("D0 chex", "D0 hep", "D4"), pch=20, bty="n",
       col=c(rgb(0,0,1,0.25), rgb(0,0.75,0.25,0.25), rgb(1,0,0,0.25)))
dev.off()


tsneRes <- Rtsne(M, perplexity=30) 
setwd("~/__Data/CyTOF/BRI_P2Pilot/")
pdf("D0_D4_tSNE.pdf", height = 10, width = 10)
plot(tsneRes$Y, col="white")
points(tsneRes$Y[which(IDs == 1 | IDs == 2 | IDs == 3 | IDs == 4), 1:2], 
      col=rgb(0,0,1,0.25), pch=20)
points(tsneRes$Y[which(IDs == 5 | IDs == 6 | IDs == 7 | IDs == 8), 1:2], 
      col=rgb(0,0.75,0.25,0.25), pch=20)
points(tsneRes$Y[which(IDs == 9 | IDs == 10 | IDs == 11 | IDs == 12), 1:2], 
      col=rgb(1,0,0,0.25), pch=20)
legend("topleft", legend=c("D0 chex", "D0 hep", "D4"), pch=20, bty="n",
       col=c(rgb(0,0,1,0.25), rgb(0,0.75,0.25,0.25), rgb(1,0,0,0.25)))
dev.off()



# library(umap)
# umapRes <- umap(aFile)
# 
# setwd("~/__Data/CyTOF/BRI_P2Pilot/")
# saveRDS(umapRes, file="umap.fNames1.RDS")

# pdf("UMAP_LIN28B_GRN15_LIN28B_POU2AF1_MLLT10.pdf")
# sel = "Sm152Di....152Sm_CD11b" # "Yb172Di....172Yb_CD20"
# myAlpha <- log2(aFile[ , sel] + 1) / log2(max(aFile[ , sel]) + 1)
# normA <- (myAlpha - min(myAlpha)) / max(myAlpha - min(myAlpha))
# plot(umapRes$layout, xaxt='n', yaxt='n', xlab="UMAP1", pch=1,
# 	 ylab="UMAP2", col="white", main=paste0(fNames[1]),
# 	 cex.main=0.7)
# points(umapRes$layout, cex=0.25, pch=20, col=rgb(0,0.5,1,normA/5))
# dev.off()


library(Rtsne)

P = 30
tsneRes = list()
for (i in 1:length(fNames)) {
   setwd("~/__Data/CyTOF/BRI_P2Pilot/")
   aFile <- read.csv(fNames[i], header=TRUE, as.is=TRUE)
   tsneRes[[i]] <- Rtsne(aFile, perplexity=P) 
   print(i)
}
names(tsneRes) <- gsub("CSV_|190807_|190801_|190802_|Allen_WB_Validation2_| subset|\\.csv", "", fNames)

setwd("~/__Data/CyTOF/BRI_P2Pilot/")
saveRDS(tsneRes, file="tsneRes.1st2.RDS")

sel = "Sm152Di....152Sm_CD11b" # "Yb172Di....172Yb_CD20"

myAlpha <- log2(aFile[ , sel] + 1) / log2(max(aFile[ , sel]) + 1)
normA <- (myAlpha - min(myAlpha)) / max(myAlpha - min(myAlpha))

# setwd("~/__Data/CyTOF/BRI_P2Pilot/")
# save(tsneRes, file=paste0("Rtsne.3120By9.Perp", P, ".RData"))
# pdf("tSNE.pdf")
plot(tsneRes$Y, pch=19, col=rgb(0,0,0,0.05), cex=0.5, 
	 xlab="tSNE 1", ylab="tSNE 2", xaxt="n", yaxt="n")
points(tsneRes$Y, cex=0.25, pch=20, col=rgb(0,0.5,1,normA))

```

