---
title: "deep2Hr"
author: "HB"
date: "7/27/2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 120),
  message = FALSE,
  warning = FALSE
)
```

# Allocate memory and use N CPUs

```{r}
library(future)
plan(strategy = "multiprocess", workers = 96)    ############### N CPUs ###################
options(future.globals.maxSize = 20 * 1024 ^ 3) # max object size

library("future.apply")
library("stats")
# future_lapply(1:10, FUN = quantile, probs = 1:3/4)
```


```{r loadData}

library("tidyverse")
library("Matrix")
library("Seurat")

CLs <- read.csv("/home/hamid.bolouri/__Data/Aldan.deep2hr/clustering/kmeans_30_clusters/clusters.csv")

mat <- Read10X("/home/hamid.bolouri/__Data/Aldan.deep2hr")
pbmc <- CreateSeuratObject(counts=mat, project="shelfLife", min.cells=3, 
                           min.features=200, meta.data=CLs)
Idents(pbmc) <- paste0("C", CLs$Cluster) # use cellRanger clusters

rm(mat)
gc()

library(SingleCellExperiment)
pbmc.sce <- as.SingleCellExperiment(pbmc)

```


# correlation to published signatures

```{r sigCorr}

setwd("~/__Data/signatures")
LM22 <- read.delim("CIBERSORT_LM22.txt", header=TRUE, row.names=1, as.is=TRUE) 
GSE107011 <- read.csv("PBMC_17of_29CellTypesRNAseqSignatures.csv", 
                      header=TRUE, row.names=1, as.is=TRUE) 
pmid30413720 <- read.csv('immunoStates_320Genes20CellTypes_signature.csv',
                         skip=2, header=TRUE, row.names=1, as.is=TRUE) # 20 cell types

library(Hmisc)
library(lsa)

# classSig: Set to one of: # LM22 # GSE107011 # pmid30413720

AdamLabels <- paste0("C", 1:30)

calcSigs <- function(classSig) {
  sharedGenes <- intersect(rownames(pbmc.sce), rownames(classSig))
  
  typesTbl = corrsTbl = list()
  for (i in 1:length(AdamLabels)) {
    iClust <- AdamLabels[i]
    j <- which(colData(pbmc.sce)$ident == iClust)
  
    selExp <- as.matrix((counts(pbmc.sce))[sharedGenes, j])
    selSig <- as.matrix(classSig[sharedGenes, ])
    corrList <- future_apply(selExp, 2, FUN=function(y) rcorr(y, selSig))
    
    rList <- lapply(corrList, function(x) x$r)
    bestMatch <- unlist(lapply(rList, function(x) {
                      x[lower.tri(x, diag=TRUE)] <- NA
                      x <- x[1, -1]
                      return(names(which(x == max(x, na.rm=TRUE))))
                      }))
  
    bestCorr <- unlist(lapply(rList, function(x) {
                      x[lower.tri(x, diag=TRUE)] <- NA
                      x <- x[1, -1]
                      return( x[which(x == max(x, na.rm=TRUE))] )
                      }))
  
    matchTbl <- rev(sort(table(bestMatch)))
    typesTbl[[i]] <- matchTbl/sum(matchTbl)
    
    corrVals = NULL
    for (iCorr in 1:length(matchTbl)) {
      corrVals <- c(corrVals, median(bestCorr[grep(names(matchTbl)[iCorr], names(bestCorr))]))
    }
    corrsTbl[[i]] <- corrVals
  }
  names(typesTbl) <- AdamLabels
  names(corrsTbl) <- AdamLabels
  
  sigsList = list()
  for (A in 1:length(AdamLabels)) {
    DF <- data.frame("cell type"=typesTbl[[A]], "correlation to signature"=corrsTbl[[A]])
    sigsList[[A]] <- DF
  }
  return(sigsList)
}

allSigs = list(); loopCount = 0
mySigs <- list(LM22, GSE107011, pmid30413720)
for (signature in mySigs) {
  loopCount <- loopCount + 1
  print(paste0(Sys.time(), "    ", loopCount))
  allSigs[[loopCount]] <- calcSigs(classSig = signature)
}
names(allSigs) <- c("LM22", "GSE107011", "pmid30413720")

setwd("~/__Data/Aldan.deep2hr")
save(allSigs, file="predictedCellTypes_Aldan2HrDeepSeq.RData")


library(ggrepel)
setwd("~/__Plots")
pdf("Aldan2HrDeepSeq_cellTypes2DPlot_allSigs.pdf", height=12, width=12)
for (indx in 1:length(AdamLabels)) {
    DF1 <- allSigs[[1]][[indx]]
    DF2 <- allSigs[[2]][[indx]]
    DF3 <- allSigs[[3]][[indx]]
    colnames(DF1)[2] = colnames(DF2)[2] = colnames(DF3)[2] = "fraction.of.cells"
    DF1$sig <- names(allSigs)[1]
    DF2$sig <- names(allSigs)[2]
    DF3$sig <- names(allSigs)[3]
    DF <- rbind(DF1, DF2, DF3)
    
    print(ggplot(DF, aes(fraction.of.cells, correlation.to.signature, label = cell.type.bestMatch, color=sig)) +
    geom_text_repel() +
    geom_point() +
    ggtitle(AdamLabels[indx]) +
    theme_classic(base_size = 16))
}
dev.off()
```

```{r seuratClusters}
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")
# VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 5000 & percent.mt < 20)

pbmc <- NormalizeData(pbmc)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)

pbmc <- ScaleData(pbmc) 
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
ElbowPlot(pbmc)

pbmc <- FindNeighbors(pbmc, dims = 1:15)
pbmc <- FindClusters(pbmc, resolution = 0.5)

pbmc <- RunUMAP(pbmc, dims = 1:15)
# use the LabelClusters function to label clusters
DimPlot(pbmc, reduction = "umap")

setwd("/home/hamid.bolouri/__Data/Aldan.deep2hr")
saveRDS(pbmc, "AldanDeep2Hr_Seurat.RDS")

pbmc.markers <- FindAllMarkers(pbmc, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
seuratClustersDETop50 = pbmc.markers %>% group_by(cluster) %>% top_n(n = 50, wt = avg_logFC)

setwd("/home/hamid.bolouri/__Data/Aldan.deep2hr")
saveRDS(pbmc.markers, file="Seurat.PBMC.markers.RDS")
save(seuratClustersDETop50, file="seuratClustersDETop50.RDS")
```

```{r seuratClusterLabels}
library(SingleCellExperiment)
pbmc.sce <- as.SingleCellExperiment(pbmc)


setwd("~/__Data/signatures")
LM22 <- read.delim("CIBERSORT_LM22.txt", header=TRUE, row.names=1, as.is=TRUE) 
GSE107011 <- read.csv("PBMC_17of_29CellTypesRNAseqSignatures.csv", 
                      header=TRUE, row.names=1, as.is=TRUE) 
pmid30413720 <- read.csv('immunoStates_320Genes20CellTypes_signature.csv',
                         skip=2, header=TRUE, row.names=1, as.is=TRUE) # 20 cell types

library(Hmisc)
library(lsa)

# classSig: Set to one of: # LM22 # GSE107011 # pmid30413720

AdamLabels <- names(table(Idents(pbmc)))

calcSigs <- function(classSig) {
  sharedGenes <- intersect(rownames(pbmc.sce), rownames(classSig))
  
  typesTbl = corrsTbl = list()
  for (i in 1:length(AdamLabels)) {
    iClust <- AdamLabels[i]
    j <- which(colData(pbmc.sce)$ident == iClust)
  
    selExp <- as.matrix((counts(pbmc.sce))[sharedGenes, j])
    selSig <- as.matrix(classSig[sharedGenes, ])
    corrList <- future_apply(selExp, 2, FUN=function(y) rcorr(y, selSig))
    
    rList <- lapply(corrList, function(x) x$r)
    bestMatch <- unlist(lapply(rList, function(x) {
                      x[lower.tri(x, diag=TRUE)] <- NA
                      x <- x[1, -1]
                      return(names(which(x == max(x, na.rm=TRUE))))
                      }))
  
    bestCorr <- unlist(lapply(rList, function(x) {
                      x[lower.tri(x, diag=TRUE)] <- NA
                      x <- x[1, -1]
                      return( x[which(x == max(x, na.rm=TRUE))] )
                      }))
  
    matchTbl <- rev(sort(table(bestMatch)))
    typesTbl[[i]] <- matchTbl/sum(matchTbl)
    
    corrVals = NULL
    for (iCorr in 1:length(matchTbl)) {
      corrVals <- c(corrVals, median(bestCorr[grep(names(matchTbl)[iCorr], names(bestCorr))]))
    }
    corrsTbl[[i]] <- corrVals
  }
  names(typesTbl) <- AdamLabels
  names(corrsTbl) <- AdamLabels
  
  sigsList = list()
  for (A in 1:length(AdamLabels)) {
    DF <- data.frame("cell type"=typesTbl[[A]], "correlation to signature"=corrsTbl[[A]])
    sigsList[[A]] <- DF
  }
  return(sigsList)
}

allSigs = list(); loopCount = 0
mySigs <- list(LM22, GSE107011, pmid30413720)
for (signature in mySigs) {
  loopCount <- loopCount + 1
  print(paste0(Sys.time(), "    ", loopCount))
  allSigs[[loopCount]] <- calcSigs(classSig = signature)
}
names(allSigs) <- c("LM22", "GSE107011", "pmid30413720")

setwd("~/__Data/Aldan.deep2hr")
save(allSigs, file="SeuratCellTypes_Aldan2HrDeepSeq.RData")


library(ggrepel)
setwd("~/__Plots")
pdf("Aldan2HrDeepSeq_SeuratCellTypes2DPlot_allSigs.pdf", height=12, width=12)
for (indx in 1:length(AdamLabels)) {
    DF1 <- allSigs[[1]][[indx]]
    DF2 <- allSigs[[2]][[indx]]
    DF3 <- allSigs[[3]][[indx]]
    colnames(DF1)[2] = colnames(DF2)[2] = colnames(DF3)[2] = "fraction.of.cells"
    DF1$sig <- names(allSigs)[1]
    DF2$sig <- names(allSigs)[2]
    DF3$sig <- names(allSigs)[3]
    DF <- rbind(DF1, DF2, DF3)
    
    print(ggplot(DF, aes(fraction.of.cells, correlation.to.signature, label = cell.type.bestMatch, color=sig)) +
    geom_text_repel() +
    geom_point() +
    ggtitle(AdamLabels[indx]) +
    theme_classic(base_size = 16))
}
dev.off()

```
