---
title: "demuxlet"
author: "HB"
date: "10/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r aifiTest}

setwd("/home/hamid.bolouri/__Data/demuxOut")
singles <- read.delim("demuxlet_out.single", header=TRUE, as.is=TRUE) # 1,338,240 x 9 

hist(singles$POSTPRB, breaks=50, col=rgb(1,0.3,0,0.5), border="white", 
     xlab="Posterior probability", main="")

indx <- which(singles$POSTPRB > 0.6)
H = hist(singles$POSTPRB[indx], breaks=50, col=rgb(1,0.3,0,0.5), border="white", 
     xlab="Posterior probability of sample assignment", main="")
sum(H$counts) # 169,359

# iFC0011 <- grepl("FC_0011", singles$SM_ID[indx]) # 78,897 barcodes are called FC_0011 @ prob > 0.6
# iFC0014 <- grepl("FC_0014", singles$SM_ID[indx]) # 90,462 barcodes are called FC_0011 @ prob > 0.6

FC0011 <- singles$BARCODE[intersect(which(grepl("FC_0011", singles$SM_ID)), indx)] # 78,897
FC0014 <- singles$BARCODE[intersect(which(grepl("FC_0014", singles$SM_ID)), indx)] # 90,462


setwd("/home/hamid.bolouri/__Data/demuxOut")
cells0011 <- read.csv("FC-0011_S1_190927_singlecell.csv", as.is=TRUE)
gd0011 <- cells0011$barcode[which(cells0011$is__cell_barcode == 1)] # 6,732

setwd("/home/hamid.bolouri/__Data/demuxOut")
cells0014 <- read.csv("FC-0014_190909_S4_singlecell.csv", as.is=TRUE)
gd0014 <- cells0014$barcode[which(cells0014$is__cell_barcode == 1)] # 8,460

length(intersect(FC0011, gd0011)) # 111
length(intersect(FC0014, gd0014)) # 117

```
