---
title: "Liger_test"
author: "HB"
date: "2/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Liger walkthrough

https://macoskolab.github.io/liger/walkthrough_pbmc.html

```{r LIGER}
library(liger)
library(cowplot)

pbmc.10x <- read.table('/Users/hamid.bolouri/Desktop/LIGER_PBMC/pbmc_10X.expressionMatrix.txt',
                       sep="\t",stringsAsFactors=F,header=T,row.names = 1)
pbmc.seqwell <- read.table('/Users/hamid.bolouri/Desktop/LIGER_PBMC/pbmc_SeqWell.expressionMatrix.txt',
                           sep="\t",stringsAsFactors=F,header=T,row.names = 1)
pbmc.data = list(tenx=pbmc.10x, seqwell=pbmc.seqwell)

# Create liger object
a.pbmc <- createLiger(pbmc.data)

a.pbmc <- normalize(a.pbmc)
# Can pass different var.thresh values to each dataset if one seems to be contributing significantly
# more genes than the other
# a.pbmc <- selectGenes(a.pbmc, var.thresh = c(0.3, 0.875), do.plot = F)

# In this case, we have a precomputed set of variable genes
s.var.genes <- readRDS('/Users/hamid.bolouri/Desktop/LIGER_PBMC/var_genes.RDS')
a.pbmc@var.genes <- s.var.genes
a.pbmc <- scaleNotCenter(a.pbmc)

# running suggestK on multiple cores can greatly decrease the runtime
# k.suggest <- suggestK(a.pbmc, num.cores = 4, gen.new = T, return.results = T, plot.log2 = F)

# For this analysis, we select a k of 22

# Take the lowest objective of three factorizations with different initializations
# Multiple restarts are recommended for initial analyses since iNMF is non-deterministic
a.pbmc <- optimizeALS(a.pbmc, k=22, thresh = 5e-5, nrep = 3)

# After the factorization, we still need to quantile align the factor loadings across the datasets. 
# Else, if we plot a t-SNE representation of the factor loadings, the data cluster by dataset.

a.pbmc <- runTSNE(a.pbmc, use.raw = T)
p1 <- plotByDatasetAndCluster(a.pbmc, return.plots = T)
# Plot by dataset
print(p1[[1]])

a.pbmc <- quantileAlignSNF(a.pbmc, resolution = 0.4, small.clust.thresh = 20)

a.pbmc <- runTSNE(a.pbmc)

pdf('LIGER_wordCloudPlots.pdf')
plotWordClouds(a.pbmc)
dev.off()


p_a <- plotByDatasetAndCluster(a.pbmc, return.plots = T) 
# Modify plot output slightly
p_a[[1]] <- p_a[[1]] + theme_classic() + theme(legend.position = c(0.85, 0.15)) + 
  guides(col=guide_legend(title = '', override.aes = list(size = 4)))

print(p_a[[1]])

# load cluster labels from Seurat 10X PBMC analysis and original SeqWell publication
clusters_prior <- readRDS('/Users/hamid.bolouri/Desktop/LIGER_PBMC/tenx_seqwell_clusters.RDS')
tenx_c <- droplevels(clusters_prior[rownames(a.pbmc@H[[1]])])
seqwell_c <- droplevels(clusters_prior[rownames(a.pbmc@H[[2]])])

# Set specific node order for cleaner visualization (can also leave to default value for 
# automatic ordering)
set_node_order = list(c(2, 6, 3, 4, 8, 1, 5, 7), c(1, 6, 2, 3, 4, 5, 7, 8, 9), c(5, 2, 3, 6, 1, 4))
makeRiverplot(a.pbmc, tenx_c, seqwell_c, min.frac = 0.05, node.order = set_node_order,
              river.usr = c(0, 1, -0.6, 1.6))

# plot t-SNE plot colored by clusters 
print(p_a[[2]]) 


```

