---
title: "Monocle3.0"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Allocate memory  and use all CPUs

```{r settings}
# Not run: had no effect
library(future)
plan(strategy = "multiprocess", workers = 8)
options(future.globals.maxSize = 20 * 1024 ^ 3)

library("future.apply")
library("stats")


#### Installation Notes:
# See: http://cole-trapnell-lab.github.io/monocle-release/monocle3/
# I had to BiocManager::install("DelayedMatrixStats")
# sudo apt-get install libudunits2-dev
# install.packages("units")
# sudo apt-get install libgdal1-dev gdal-bin libproj-dev proj-data proj-bin libgeos-dev
# I installed the 2 python packages needed via pip

```

## HB 12June2019 - based on Monocle3.0 tutorial

``` {r getSet}
setwd("~/__Data")
library("Matrix")
normalizedPBMC <- get(load("SeuratNormalizedCounts_GRCh38_filteredMT.RData"))

#### NB: Subsetting selPBMCs ######################################################
indx <- intersect(grep("BRISL2", colnames(normalizedPBMC)),
                 grep("2h$|4h$|6h$|-8h$", colnames(normalizedPBMC)))
selPBMC <- normalizedPBMC[ , indx]
PBMC.IDs <- unlist(lapply(strsplit(colnames(selPBMC), "-"), function(x) x[1]))
timePoints <- unlist(lapply(strsplit(colnames(selPBMC), "-"), function(x) x[3]))

setwd("~/__Data"); getwd()
CLs <- read.csv("clusters.csv", as.is=TRUE)
clusterIDs <- unlist(lapply(strsplit(CLs$Barcode, "-"), function(x) x[1]))
CLs <- CLs[match(PBMC.IDs, clusterIDs), ]
CLs$Barcode <- colnames(selPBMC)
colnames(CLs) <- c("ID", "group")
CLs$group<- as.factor(CLs$group)
rownames(CLs) <- CLs$ID
geneMeta <- data.frame("gene_short_name"=rownames(selPBMC))
rownames(geneMeta) <- rownames(selPBMC)


library(monocle3)
# cds <- load_cellranger_data("cell_ranger_output")
cds <- new_cell_data_set(selPBMC, cell_metadata=CLs,
                        gene_metadata=geneMeta)

# Late addition to allow coloring by timepoint:
colData(cds)$timePoint <- timePoints
```


## Monocle3 run

```{r tutorial}
cds <- preprocess_cds(cds, num_dim = 100)
cds <- reduce_dimension(cds, reduction_method="UMAP", cores=8)  ### NB cores == 8 but ran on only 1 CPU !!!
# cds <- reduce_dimension(cds, reduction_method="tSNE", cores=8)  ### NB cores == 8 but ran on only 1 CPU !!!
# cds <- reduce_dimension(cds, reduction_method="PCA", cores=8)   ### NB cores == 8 but ran on only 1 CPU !!!

# plot_cells(cds, reduction_method="UMAP")

gc()
cds <- cluster_cells(cds, reduction_method="UMAP")
# head(partitions(cds, reduction_method = "UMAP")) # partictions = super-clusters for trajectory-building
# head(clusters(cds, reduction_method = "UMAP"))

# cds_subset <- choose_cells(cds) ### !!! Interactive !!! ###
# 
# gene_fits <- fit_models(cds_subset[1:100,],
#                         model_formula_str = "~cluster")
# fit_coefs <- coefficient_table(gene_fits)
# head(fit_coefs)
# 
# marker_genes <- top_markers(cds) # Slow. Using "futures" above did not parallelize it.
# tops_sig <- subset(marker_genes, marker_test_q_value < .05)

```

```{r trajectoryAnalysis}
cds <- learn_graph(cds, use_partition=TRUE, close_loop=FALSE,
                   learn_graph_control=list(euclidean_distance_ratio=1.5,
                   geodesic_distance_ratio=0.5,
                   minimal_branch_len=20,
                   prune_graph=TRUE))
setwd("~/__Data")
pdf("BRISL2_Monocle3_trajectory_no18Hr.pdf")
plot_cells(cds, reduction_method="UMAP", 
           color_cells_by="timePoint", group_cells_by="cluster", 
           show_trajectory_graph=TRUE, alpha=0.5,
           label_cell_groups=FALSE,
           label_groups_by_cluster=FALSE, 
           label_branch_points=FALSE,
           label_roots=FALSE, label_leaves=FALSE,
           trajectory_graph_color="black",
           trajectory_graph_segment_size=0.75,
           norm_method="log")
dev.off()
```

## Per Cluster Trajectories

```{r perClusterTrajectories}
setwd("~/__Data")
library("Matrix")
normalizedPBMC <- get(load("SeuratNormalizedCounts_GRCh38_filteredMT.RData"))

setwd("~/__Data")
CLs <- read.csv("clusters.csv", as.is=TRUE)
clusterIDs <- unlist(lapply(strsplit(CLs$Barcode, "-"), function(x) x[1]))
colnames(CLs) <- c("ID", "group")

PBMC.IDs <- unlist(lapply(strsplit(colnames(normalizedPBMC), "-"), function(x) x[1]))
indx <- match(clusterIDs, PBMC.IDs)
CLs <- CLs[which(!is.na(indx)), ]
selPBMC <- normalizedPBMC[ , indx[!is.na(indx)]]

clusterIDs <- unlist(lapply(strsplit(CLs$ID, "-"), function(x) x[1]))
PBMC.IDs <- unlist(lapply(strsplit(colnames(selPBMC), "-"), function(x) x[1]))

indx <- intersect(grep("BRISL2", colnames(selPBMC)),
                 grep("2h$|4h$|6h$|-8h$", colnames(selPBMC)))
selPBMC <- selPBMC[ , indx]
CLs <- CLs[indx, ]

clusterIDs <- unlist(lapply(strsplit(CLs$ID, "-"), function(x) x[1]))
PBMC.IDs <- unlist(lapply(strsplit(colnames(selPBMC), "-"), function(x) x[1]))
# identical(clusterIDs, PBMC.IDs) # TRUE

iClust <- grep("6", CLs$group)
CLs <- CLs[iClust, ]
selPBMC <- selPBMC[ , iClust]

indx <- which(!duplicated(colnames(selPBMC)))
selPBMC <- selPBMC[ , indx]
CLs <- CLs[indx, ]

clusterIDs <- unlist(lapply(strsplit(CLs$ID, "-"), function(x) x[1]))
PBMC.IDs <- unlist(lapply(strsplit(colnames(selPBMC), "-"), function(x) x[1]))
identical(clusterIDs, PBMC.IDs) # TRUE
timePoints <- unlist(lapply(strsplit(colnames(selPBMC), "-"), function(x) x[3]))

CLs$group<- as.factor(CLs$group)
rownames(CLs) <- colnames(selPBMC)

geneMeta <- data.frame("gene_short_name"=rownames(selPBMC))
rownames(geneMeta) <- rownames(selPBMC)



library(monocle3)
# cds <- load_cellranger_data("cell_ranger_output")
cds <- new_cell_data_set(selPBMC, cell_metadata=CLs,
                        gene_metadata=geneMeta)

# Late addition to allow coloring by timepoint:
colData(cds)$timePoint <- timePoints


cds <- preprocess_cds(cds, num_dim = 100)
cds <- reduce_dimension(cds, reduction_method="UMAP", cores=8)  ### NB cores == 8 but ran on only 1 CPU !!!
# cds <- reduce_dimension(cds, reduction_method="tSNE", cores=8)  ### NB cores == 8 but ran on only 1 CPU !!!
# cds <- reduce_dimension(cds, reduction_method="PCA", cores=8)   ### NB cores == 8 but ran on only 1 CPU !!!

# plot_cells(cds, reduction_method="UMAP")

gc()
cds <- cluster_cells(cds, reduction_method="UMAP")


cds <- learn_graph(cds, use_partition=TRUE, close_loop=FALSE,
                   learn_graph_control=list(euclidean_distance_ratio=1.5,
                   geodesic_distance_ratio=0.5,
                   minimal_branch_len=20,
                   prune_graph=TRUE))
setwd("~/__Plots")
pdf("BRISL2_C6__Monocle3_trajectory_no18Hr.pdf")
plot_cells(cds, reduction_method="UMAP", 
           color_cells_by="timePoint", group_cells_by="cluster", 
           show_trajectory_graph=TRUE, alpha=0.5,
           label_cell_groups=FALSE,
           label_groups_by_cluster=FALSE, 
           label_branch_points=FALSE,
           label_roots=FALSE, label_leaves=FALSE,
           trajectory_graph_color="black",
           trajectory_graph_segment_size=0.75,
           norm_method="log")
dev.off()

```