---
title: "Tony2HrBatches"
author: "HB"
date: "8/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  tidy = TRUE,
  tidy.opts = list(width.cutoff = 120),
  message = FALSE,
  warning = FALSE
)
```

# Allocate memory and use N CPUs

```{r}
library(future)
plan(strategy = "multiprocess", workers = 8)    ############### N CPUs ###################
options(future.globals.maxSize = 20 * 1024 ^ 3) # max object size

library("future.apply")
library("stats")
```


```{r loadData}

library("tidyverse")
library("Matrix")
library("Seurat")

CLs <- read.csv("/home/hamid.bolouri/__Data/Aldan.deep2hr/clustering/kmeans_30_clusters/clusters.csv")

mat <- Read10X("/home/hamid.bolouri/__Data/Aldan.deep2hr")
pbmcDeep <- CreateSeuratObject(counts=mat, project="shelfLife", min.cells=3, 
                           min.features=200, meta.data=CLs)
Idents(pbmcDeep) <- paste0("C", CLs$Cluster) # use cellRanger clusters

rm(mat)
gc()

setwd("/home/hamid.bolouri/__Data/Aldan.SLE.HD")
pbmcAll <- get(load("Seurat.pbmc.pre.scTransform_shelfLifeALL.RData"))

setwd("~/__Data/shelfLifeSLE/")
meta <- get(load("Aggr_Human_Immunology_RTX-850-856_GRCh38-3.0.0_premrna_samp.dat_v3_reads.RData"))
tags <- unlist(lapply(sapply(meta[ ,1], function(x) strsplit(x, "BRISL")), function(y) y[1]))
tagsHD <- tags[grep("BRISL2|BRISL3|BRISL4", names(tags))]
tagsHD2 <- tagsHD[grep("-2h", names(tagsHD))]

pbmc2h <- pbmcAll[ , match(tagsHD2, colnames(pbmcAll))]

sharedGenes <- intersect(rownames(pbmc2h), rownames(pbmcDeep))
pbmc2h <- pbmc2h[match(sharedGenes, rownames(pbmc2h)), ]
pbmcDeep <- pbmcDeep[match(sharedGenes, rownames(pbmcDeep)), ]

pbmc.combined <- merge(pbmcDeep, y = pbmc2h, add.cell.ids = c("deep", "norm"), project = "batchTest2h")
setwd("~/__Data")
saveRDS(pbmc.combined, file="pbmc.2h.combinedDeepNorm.RDS")

pbmc2HrSCT <- SCTransform(object = pbmc.combined, verbose = FALSE, 
                          vars.to.regress = NULL, conserve.memory = FALSE)
setwd("~/__Data")
saveRDS(pbmc2HrSCT, file="pbmc.2h.combinedSCT.RDS")

pbmc2HrSCT <- RunPCA(pbmc2HrSCT)
pbmc2HrSCT <- RunTSNE(pbmc2HrSCT)

# DimPlot(pbmc2HrSCT, reduction = "pca", pt.size = 0.5, group.by = 'ident')

PCA <- Embeddings(pbmc2HrSCT, reduction = "tsne")[ , 1:2]
DEEP <- grep("^deep", rownames(PCA))
NORM <- grep("^norm", rownames(PCA))

setwd("~/__Plots/")
pdf("shelfLife_2h_highLowDepth_batchComparison.pdf")
plot(PCA, col="white", pch=1, xaxt='n', yaxt='n')
points(PCA[DEEP, ], pch=19, col="coral", cex=0.5)
points(PCA[NORM, ], pch=19, col=rgb(0,0.5,1,0.25), cex=0.5)
legend("bottomleft", legend=c("2hr_deep", "2hr_norm"), pch=c(19, 19), 
       col=c("coral", rgb(0,0.5,1,0.75)), bty="n")
dev.off()

```


