---
title: "tSNE.2h.4h.aging"
author: "HB"
date: "7/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(future)
plan(strategy = "multiprocess", workers = 8)    ############## set number of CPUs #################
options(future.globals.maxSize = 20 * 1024 ^ 3)

library("future.apply")
library("stats")
```


## 


```{r xxxx}
setwd("/home/hamid.bolouri/__Data/Aldan.SLE.HD")
normalizedPBMC <- get(load("SeuratNormalizedCountsALL_GRCh38_filteredMT.RData"))

setwd("~/__Data/shelfLife_LSE.v.HD")
coords <- read.csv("HD.SLE.tSNE.cellRanger.csv", row.names=1, as.is=TRUE)
annot <- read.csv("library_metadata.csv", as.is=TRUE)
CLs <- read.csv("clustersK10.csv")


setwd("~/__Data/shelfLifeSLE/")
meta <- get(load("Aggr_Human_Immunology_RTX-850-856_GRCh38-3.0.0_premrna_samp.dat_v3_reads.RData"))

tags <- unlist(lapply(sapply(meta[ ,1], function(x) strsplit(x, "BRISL")), function(y) y[1]))
tags24 <- tags[grep("-2h|-4h", names(tags))]

coords <- coords[match(tags24, rownames(coords)), ]

XY.7 <- coords[match(CLs$Barcode[CLs$Cluster == 7], rownames(coords)), ]

plot(coords, cex=0.5, pch=20, col=rgb(0,0,0,0.05), xaxt='n', yaxt='n')
points(XY.7, cex=0.5, pch=20, col=rgb(1,0.5,0,0.5))


# Marker plots:
gene = "CD22"
indx <- match(rownames(coords), colnames(normalizedPBMC))
indx <- indx[!is.na(indx)]
gExp <- normalizedPBMC[gene, indx]
gExp <- gExp / max(gExp)

expXY <- coords[match(names(gExp), rownames(coords)), ]

plot(coords, cex=0.5, pch=20, col=rgb(0,0,0,0.05), xaxt='n', yaxt='n', main=paste0(gene))
points(expXY, cex=0.5, pch=20, col=rgb(1,0.5,0,gExp))

```
